default_platform(:ios)

platform :ios do
  desc "Build and upload EvoWit to TestFlight"
  lane :beta do
    sh("xcodegen generate")
    build_app(
      project: "EvoWit.xcodeproj",
      scheme: "EvoWit",
      export_method: "app-store",
      output_directory: "../build"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
